const careerJobs = [
    { title: "Chauffeur de Uber", salary: 2000, type: "Legal" },
    { title: "Mécanicien", salary: 2500, type: "Legal" },
    { title: "Vendeur chez Ammu-Nation", salary: 1800, type: "Legal" },
    { title: "Barman", salary: 1500, type: "Legal" },
    { title: "Infirmier", salary: 3500, type: "Legal" },
    { title: "Avocat Junior", salary: 5000, type: "Legal" },
    { title: "Agent de sécurité", salary: 2200, type: "Legal" },
    { title: "Journaliste", salary: 2800, type: "Legal" },
    { title: "Livreur de pizzas", salary: 1200, type: "Legal" },
    { title: "Nettoyeur de scènes de crime", salary: 4000, type: "Legal" },
    { title: "Informaticien", salary: 4500, type: "Legal" },
    { title: "Éboueur", salary: 2500, type: "Legal" },
    { title: "Docks Worker", salary: 2300, type: "Legal" },
    { title: "Croupier au Casino", salary: 3000, type: "Legal" },
    { title: "Garde du corps", salary: 4500, type: "Legal" },
    { title: "Plombier", salary: 2600, type: "Legal" },
    { title: "Électricien", salary: 2700, type: "Legal" },
    { title: "Charpentier", salary: 2400, type: "Legal" },
    { title: "Boucher", salary: 2100, type: "Legal" },
    { title: "Boulanger", salary: 1900, type: "Legal" },
    { title: "Fleuriste", salary: 1600, type: "Legal" },
    { title: "Pharmacien", salary: 4800, type: "Legal" },
    { title: "Architecte", salary: 6000, type: "Legal" },
    { title: "Ingénieur Civil", salary: 5500, type: "Legal" },
    { title: "Comptable", salary: 4200, type: "Legal" },
    { title: "Analyste Financier", salary: 5200, type: "Legal" },
    { title: "Courtier Immo", salary: 3500, type: "Legal" },
    { title: "Photographe", salary: 2200, type: "Legal" },
    { title: "Graphiste", salary: 2800, type: "Legal" },
    { title: "Web Developer", salary: 4700, type: "Legal" },
    { title: "Data Scientist", salary: 6500, type: "Legal" },
    { title: "UX Designer", salary: 4300, type: "Legal" },
    { title: "Social Media Manager", salary: 3000, type: "Legal" },
    { title: "Marketing Manager", salary: 5000, type: "Legal" },
    { title: "Chef de Cuisine", salary: 4500, type: "Legal" },
    { title: "Serveur", salary: 1400, type: "Legal" },
    { title: "Receptionniste", salary: 1800, type: "Legal" },
    { title: "Concierge de luxe", salary: 3200, type: "Legal" },
    { title: "Pilote d'avion privé", salary: 8000, type: "Legal" },
    { title: "Hôtesse de l'air", salary: 3000, type: "Legal" },
    { title: "Conducteur de train", salary: 3500, type: "Legal" },
    { title: "Capitaine de Yacht", salary: 7000, type: "Legal" },
    { title: "Moniteur d'auto-école", salary: 2400, type: "Legal" },
    { title: "Coach Sportif", salary: 3000, type: "Legal" },
    { title: "Kinésithérapeute", salary: 4000, type: "Legal" },
    { title: "Dentiste", salary: 7500, type: "Legal" },
    { title: "Vétérinaire", salary: 4500, type: "Legal" },
    { title: "Toiletteur", salary: 1700, type: "Legal" },
    { title: "Jardinier", salary: 2000, type: "Legal" },
    { title: "Serrurier", salary: 3000, type: "Legal" },
    { title: "Tatoueur", salary: 3500, type: "Legal" },
    { title: "DJ", salary: 2500, type: "Legal" },
    { title: "Organisateur de mariages", salary: 3800, type: "Legal" },
    { title: "Bibliothécaire", salary: 2100, type: "Legal" },
    { title: "Professeur", salary: 3200, type: "Legal" },
    { title: "Chercheur", salary: 4500, type: "Legal" },
    { title: "Traducteur", salary: 2800, type: "Legal" },
    { title: "Psychologue", salary: 4200, type: "Legal" },
    { title: "Conseiller d'orientation", salary: 2600, type: "Legal" },
    { title: "Pompier", salary: 3300, type: "Legal" },
    { title: "Policier (LSPD)", salary: 3500, type: "Legal" },
    { title: "Détective Privé", salary: 4000, type: "Legal" },
    { title: "Garde Forestier", salary: 2500, type: "Legal" },
    { title: "Facteur", salary: 1900, type: "Legal" },
    { title: "Guichetier Banque", salary: 2200, type: "Legal" },
    { title: "Tailleur", salary: 2300, type: "Legal" },
    { title: "Bijoutier", salary: 4500, type: "Legal" },
    { title: "Opticien", salary: 3800, type: "Legal" },
    { title: "Horloger", salary: 3200, type: "Legal" },
    { title: "Ebéniste", salary: 2900, type: "Legal" },
    { title: "Forgeron Moderne", salary: 3100, type: "Legal" },
    { title: "Maçon", salary: 2500, type: "Legal" },
    { title: "Peintre en bâtiment", salary: 2200, type: "Legal" },
    { title: "Carreleur", salary: 2400, type: "Legal" },
    { title: "Grutier", salary: 3800, type: "Legal" },
    { title: "Foreur Pétrolier", salary: 5500, type: "Legal" },
    { title: "Marin-Pêcheur", salary: 2800, type: "Legal" },
    { title: "Agriculteur Urbain", salary: 2100, type: "Legal" },
    { title: "Apiculteur", salary: 1800, type: "Legal" },
    { title: "Sommelier", salary: 4000, type: "Legal" },
    { title: "Oenologue", salary: 4800, type: "Legal" },
    { title: "Chocolatier", salary: 2500, type: "Legal" },
    { title: "Pâtissier", salary: 2300, type: "Legal" },
    { title: "Glacier", salary: 1600, type: "Legal" },
    { title: "Fromager", salary: 2200, type: "Legal" },
    { title: "Vigneron", salary: 3500, type: "Legal" },
    { title: "Parfumeur", salary: 5500, type: "Legal" },
    { title: "Mannequin", salary: 3000, type: "Legal" },
    { title: "Acteur de seconde zone", salary: 2000, type: "Legal" },
    { title: "Cascadeur", salary: 4500, type: "Legal" },
    { title: "Maquilleur Pro", salary: 2800, type: "Legal" },
    { title: "Coiffeur", salary: 2100, type: "Legal" },
    { title: "Esthéticienne", salary: 1900, type: "Legal" },
    { title: "Masseur", salary: 2500, type: "Legal" },
    { title: "Laveur de vitres de gratte-ciel", salary: 3500, type: "Legal" },
    { title: "Cordiste", salary: 3800, type: "Legal" },
    { title: "Scaphandrier", salary: 6000, type: "Legal" },
    { title: "Démineur", salary: 7000, type: "Legal" },
    { title: "Chirurgien", salary: 12000, type: "Legal" },
    { title: "Neuroscientifique", salary: 9000, type: "Legal" }
];

module.exports = { careerJobs };
